version: "3.9"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - mangakatre

    mangakatre:
        image: bitnami/php-fpm:latest
        ports:
          - "9000:9000"
        volumes:
            - ./src:/var/www/html